language: cpp
compiler:
  - gcc

before_install:
  - curl http://download.opensuse.org/repositories/science:/dlr/xUbuntu_16.04/Release.key | sudo apt-key add -
  - echo "deb http://download.opensuse.org/repositories/science:/dlr/xUbuntu_16.04/ /" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes cmake cmake-data gfortran
  
before_script:
  - mkdir build
  - cd build

script: 
  - cmake -DBUILD_SHARED_LIBS=ON -DTIXI_BUILD_TESTS=ON ..
  - make
  - cd tests
  - ./TIXI-unittests
